name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker on macOS
      if: runner.os == 'macOS'
      run: |
        brew install --cask docker
        open /Applications/Docker.app
        while ! docker system info > /dev/null 2>&1; do sleep 1; done
    - name: Start Docker service on macOS
      if: runner.os == 'macOS'
      run: |
        sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended &
        while ! docker system info > /dev/null 2>&1; do sleep 1; done
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag renv_pak_debug:$(date +%s)
